---

- name: execute ansible drop-in role
  hosts: all
  vars:
    - dropin_role: "{{ lookup('env','ANSIBLE_DROPIN_ROLE') }}"
  roles:
    - "{{ dropin_role }}"

- name: start OMD site "demo"
  hosts: all
  tasks:
    - command: omd start demo
      register: site_started


## Web server is started by playbook_starter.sh when ansible-playbook has ended.
