---

- name: execute ansible drop-in role
  hosts: all
  vars:
    - dropin_role: "{{ lookup('env','ANSIBLE_DROPIN_ROLE') }}"
  roles:
    - "{{ dropin_role }}"

- name: start OMD site "demo"
  hosts: all
  tasks:
    - command: omd start demo
      register: site_started

- name: Start Apache web server
  hosts: all
  tasks:
    - command: /usr/sbin/apache2ctl -D FOREGROUND -k start
      when: site_started.rc == 0
