name: Docker latest

on:
  push:
    branches:
      - latest
    tags-ignore:
      - '*'

jobs:
  push_to_registries:
    name: Push Docker image to github and dockerhub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        target:
          - omd-labs-centos
          - omd-labs-debian
          - omd-labs-ubuntu
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile.${{ matrix.target }}
          build-args: OMD_VERSION=${{ github.ref }}
          tags: consol/${{ matrix.target }}:latest
      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile.${{ matrix.target }}
          build-args: OMD_VERSION=${{ github.ref }}
          tags: docker.pkg.github.com/consol/omd-labs-docker/${{ matrix.target }}:latest
